### ISSUE TITLE
lox

### ISSUE THREAD

**Issue by archhhh** [PZDuck/todo-list#1]
pidor

**Comment by PZDuck** [comment]
> 
> 
> pidor

[http://risovach.ru/upload/2014/10/mem/a-mozhet-ty-pidor_64763466_orig_.jpeg](url)

**Comment by PZDuck** [comment]
![image](https://user-images.githubusercontent.com/45107177/72195008-5cbf0400-33de-11ea-848d-31f0740f3294.png)

**Comment by PZDuck** [comment]
> 
> 
> pidor

![Uploading image.png…]()

**Comment by PZDuck** [comment]
> 
> 
> pidor

![image](https://user-images.githubusercontent.com/45107177/72195026-75c7b500-33de-11ea-866b-9cbbeff34af8.png)
